### ISSUE TITLE
MacOS bindings conflict

### ISSUE THREAD

**Issue by rpeshkov** [ajtoo/vscode-org-mode#100]
Extension introduces keybindings "alt+left" and "alt+right" (option+left and option+right on mac) for switching the context. On MacOS those bindings are actually used to jump by words in text, like ctrl+left and ctrl+right on Windows.

What do you think about remapping it to something like "ctrl+alt+[" and "ctrl+alt+]" by default?

**Comment by xxbc** [comment]
yeah agreeing here, the alt-left and alt-right bindings do nothing and pop up a warning that says: "no context to modify" Can these be remapped or can advice be given on how to remap ourselves within keybindings.json? thanks

**Comment by xxbc** [comment]
@rpeshkov actually just remapped myself and now no problem -- add the following to your keybindings.json file

`// Place your key bindings in this file to overwrite the defaults
[
    {
        "key": "ctrl+alt+right",
        "command": "org.incrementContext",
        "when": "editorLangId == 'org'"
    },
    {
        "key": "ctrl+alt+left",
        "command": "org.decrementContext",
        "when": "editorLangId == 'org'"
    },
]`

**Comment by rpeshkov** [comment]
@xxbc, yep, it’s easy to remap it back, but it’s very annoying that there is remapping of standard behavior. I guess I’ll raise proposal for vscode team for adding additional control on extension contributed keybindings. I would like to see the option like “Disable contributed keybindings”. When selected, none of contributed keybindings should be applied and it will be your responsibility to map them as you want.
