### ISSUE TITLE
Support for Syntax Highlighting in Code Blocks

### ISSUE THREAD

**Issue by humanfactors** [ajtoo/vscode-org-mode#103]
It would be nice to see syntax highlighting in a similar fashion to the Markdown plugin. I am not very familiar with TypeScript, and from looking at the [Markdown plugin that comes packaged with vscode](https://github.com/Microsoft/vscode/blob/master/extensions/markdown-basics/syntaxes/markdown.tmLanguage.json), my understanding is that this may be a significant job. I had limited success modifying the regex patterns and there could be a more efficient way.

**Comment by AdrieanKhisbe** [comment]
I'm working on it :)
Will soon open a Pr for it.
So far working well:

Teaser
<img width="286" alt="capture d ecran 2018-05-28 23 52 48" src="https://user-images.githubusercontent.com/2601132/40630727-67772c00-62d5-11e8-8cee-b0ca77f01e57.png">
