### ISSUE TITLE
What are the default keybindings?

### ISSUE THREAD

**Issue by gsaga** [ajtoo/vscode-org-mode#109]
The readme doesn't mention it anywhere? Where can I find them?

**Comment by mgwelch** [comment]
Why did you close this? Did you find them? I have the same question.

**Comment by sipi** [comment]
Have a look to the [wiki](https://github.com/ajtoo/vscode-org-mode/wiki), there are default keybindings for different purposes on different pages. Otherwise, in VSCode ``File > Preferences > Keyboard Shortcuts``, search for ``org:`` and you will find all keybindings.
