### ISSUE TITLE
Does anyone still maintain this repository ? Is it appropriate to consider a change of maintainers ?

### ISSUE THREAD

**Issue by sipi** [ajtoo/vscode-org-mode#119]
Hi @ajtoo, 
are you still working on this project? interesting on?
is your time away temporary?

Should other maintainers be considering taking over the project?

I would point out that this is by no means a blame, and I'm not personally really interested in taking over the project (but I can help if needed). It's just a question to clarify the future of this very useful extension. 

In any case, thank you for the work done.

**Comment by ajtoo** [comment]
@sipi Hi, I would love to have you on board as a team member on this project! Life seems to have taken me down a very personally busy path lately and I haven't had any time to dedicate to this. I think this project could use a much needed push forward. Email me at ajtoo.dev@gmail.com and let's set up some time to chat about pushing the extension forward!

**Comment by sipi** [comment]
Hi, I'm happy to read you :)
I'm going to send you an e-mail.
read you soon.
