### ISSUE TITLE
Insert Heading Respect Content is breaking lines

### ISSUE THREAD

**Issue by jsonreeder** [ajtoo/vscode-org-mode#54]
When I call `Org: Insert Heading Respect Content` on the middle of a line, it breaks that line:

![respect_content](https://cloud.githubusercontent.com/assets/10589114/24843814/103dfcc2-1d5b-11e7-99df-bb1d5855df18.gif)

Instead, it should insert a new header below without breaking the line. The current behavior would be appropriate to `Insert Heading` but not `respect content`.

**Comment by jsonreeder** [comment]
An additional note here: it seems that this is happening only when the header is the last line of the file (as in the example screenshot), but not when the header is on any other line.

**Comment by ajtoo** [comment]
PR to fix issue has been merged
