### ISSUE TITLE
Emphasis and other highlighting are greedy/inaccurate to org

### ISSUE THREAD

**Issue by porglezomp** [ajtoo/vscode-org-mode#75]
If you have multiple emphasized/italicized/marked as code on a line, then they're consumed greedily.

For example **\*this\*, is displayed as \*this\***.
When I would expect **\*this\*** to be displayed like **\*this\***.

**Comment by PGilbertSchmitt** [comment]
I think it's been patched, but the resulting fix hasn't been pushed to the
vs market. I'll get published today or tomorrow. I apologize. We are all
currently working on other projects at the moment, so this one has been
pushed to the side.

**Comment by hastebrot** [comment]
Commit that fixes this was https://github.com/ajtoo/vscode-org-mode/commit/7dcaed0678b5aedf6bae0e56933ea5de5e8f1eb8.

**Comment by rpeshkov** [comment]
@hastebrot verbatim and code are now non-greedy as well. Check PR #101

**Comment by sipi** [comment]
solved
