### ISSUE TITLE
Time Tracking / Clock in and out

### ISSUE THREAD

**Issue by k0105** [ajtoo/vscode-org-mode#77]
Hi,

does this project support time tracking via clock in and clock out? If not, I hereby open a feature request for it. I outlined how this might work over at the Orgzly repo, cmp. https://github.com/orgzly/orgzly-android/issues/15

Unfortunately, I currently have no free minute to contribute the feature, but I'm sure there is widespread interest in it, since time tracking is one of the most popular use cases [behind todo lists and notes, of course].

Best wishes,
k0105

**Comment by fishbacon** [comment]
Looks like this might be outdated: https://github.com/ajtoo/vscode-org-mode/commit/49229bd23369d8d554feb180c3a2207a2db6270e

Someone should consider closing the issue 👍

**Comment by ajtoo** [comment]
@fishbacon thanks for catching that, closing the issue

**Comment by k0105** [comment]
Thank you from me as well.
