### ISSUE TITLE
TODO context switching only works when no space proceeds the *

### ISSUE THREAD

**Issue by Kinths** [ajtoo/vscode-org-mode#94]
Firstly, I am not sure if this is a bug or a feature as I am not sure whether you can do this in the original ORG mode.

When you use context switch (alt + left/right) on a line that contains a TODO, it will only work if the * is the first char on the line. However, it is useful to be able to have indented TODOs to help with organisation and structure of a file. You can technically do this by adding more *s but it would be nice to have the indentation option.

I have created a fix for this and will create a pull request once I figure out how (this is my first attempt at a contribution to someone else's project)

EDIT: Pull request made #95

**Comment by hi2u** [comment]
@AndrewJRichardson / @ajtoo (or anyone else using this feature)...

Does this fix still work for you?

Alt + left/right is only working for me on lines that begin with `*`
