### ISSUE TITLE
solarized light theme not showing TODO in a different color

### ISSUE THREAD

**Issue by sean-sh** [ajtoo/vscode-org-mode#98]
Hi,
In other themes the keyword TODO shows up in a different color than the rest of the line, but not in Solarized Light.
Here's a screenshot:
![screen shot 2018-02-26 at 17 45 55](https://user-images.githubusercontent.com/9609837/36676588-1d052726-1b1d-11e8-8489-a4836fc89783.png)

Using vscode 1.20.0 on mac.

And thank you very much for developing this extension

**Comment by sipi** [comment]
Hi,
as written in the Readme file:

> Colorization, bolding, italicization, and other modes of highlighting are handled differently by different themes. We have prioritized supporting the default VS Code themes (Dark+ and Light+). This prioritization means that some colors may not appear as expected in other themes, or that opportunities for more variance have been missed.

For information, there is similar issue with this theme and TypeScript :
![dark](https://user-images.githubusercontent.com/586230/45482940-b0203400-b74f-11e8-8cb0-f45f58bc90e8.png)
![solar](https://user-images.githubusercontent.com/586230/45482987-d6de6a80-b74f-11e8-8e01-8800bdfb2c20.png)

We're sorry, but we don't have time to investigate this issue. However, Feel free to suggest modifications by a Pull Request as long as these modification does not affect default VS Code themes (Dark+ and Light+).
